### ISSUE TITLE
GetParameterByName: Length values from rebar elements are not converted to millimeters.

### ISSUE THREAD

**Issue by eibre** [DynamoDS/DynamoRevit#1041]
## Dynamo version

1.0.0.1180
## Revit version

Revit 2017
## Operating system

Windows 10
## What did you do?

Used the GetParameterValueByName node to extract length parameters of a Rebar element
## What did you expect to see?

The parameter value in millimeters
## What did you see instead?

The parameter value in feet

![image](https://cloud.githubusercontent.com/assets/5968613/16176062/36f55f62-3603-11e6-9e93-f28997acaa25.png)

**Comment by eibre** [comment]
It has probably something to do with this:

> Unit type DUT_METERS: There are no less than 21 different valid unit types in which it may appear:
> 
> Length, SheetLength, HVAC_DuctSize, HVAC_Roughness, PipeSize, Piping_Roughness, WireSize, DecSheetLength, Electrical_CableTraySize, Electrical_ConduitSize, Reinforcement_Length, HVAC_DuctInsulationThickness, HVAC_DuctLiningThickness, PipeInsulationThickness, Bar_Diameter, Crack_Width, Displacement_Deflection, Reinforcement_Cover, Reinforcement_Spacing, Section_Dimension, Section_Property.

http://thebuildingcoder.typepad.com/blog/2013/11/mapping-display-unit-type-to-unit-types.html

**Comment by ksobon** [comment]
Hi @eibre,

So this is caused by the fact that Revit stores all of the values internally in Feet. Always. Now, the display unit might be set to mm but the value that is returned will be in FT. That's just a strange Revit behavior but it is what it is. I can imagine that we can obtain the `DisplayUnitType` from the `Parameter` itself and then convert the value stored in there to what is normally displayed by Revit UI. 

@mjkkirschner @aparajit-pratap 

So it appears that we are already checking a handful of unit types but this specific one here is not covered. `ReinforcementLength` is not on a list here: 

![image](https://cloud.githubusercontent.com/assets/529781/22400314/3b961648-e57f-11e6-9838-471d6db24351.png)

We should add that in or figure out a different way to handle this rather than checking bunch of types with if statements. For now I can add Length, Area and Volume like this: 

```
internal static bool IsConvertableParameterType(ParameterType paramType)
        {
            return paramType == ParameterType.Length || paramType == ParameterType.Area ||
                paramType == ParameterType.Volume || paramType == ParameterType.Angle ||
                paramType == ParameterType.Slope || paramType == ParameterType.Currency ||
                paramType == ParameterType.MassDensity || paramType == ParameterType.ReinforcementLength ||
                paramType == ParameterType.ReinforcementArea || paramType == ParameterType.ReinforcementVolume;
        }
```
```
        [SupressImportIntoVM]
        internal static UnitType ParameterTypeToUnitType(ParameterType parameterType)
        {
            switch (parameterType)
            {
                case ParameterType.Length:
                    return UnitType.UT_Length;
                case ParameterType.ReinforcementLength:
                    return UnitType.UT_Length;
                case ParameterType.Area:
                    return UnitType.UT_Area;
                case ParameterType.ReinforcementArea:
                    return UnitType.UT_Area;
                case ParameterType.Volume:
                    return UnitType.UT_Volume;
                case ParameterType.ReinforcementVolume:
                    return UnitType.UT_Volume;
                case ParameterType.Angle:
                    return UnitType.UT_Angle;
                case ParameterType.Slope:
                    return UnitType.UT_Slope;
                case ParameterType.Currency:
                    return UnitType.UT_Currency;
                case ParameterType.MassDensity:
                    return UnitType.UT_MassDensity;
                default:
                    throw new Exception(Properties.Resources.UnitTypeConversionError);
            }
        }
```

So we get this: 

![image](https://cloud.githubusercontent.com/assets/529781/22400383/0802b4a6-e581-11e6-9e06-3869034a4adb.png)


Cheers!

**Comment by eibre** [comment]
Solved
