### ISSUE TITLE
Wish: Get rid of version switcher in Revit ribbon

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#1180]
## Dynamo version

Any

## Revit version

Any

## Operating system

Any

## What did you do? 

Start Dynamo from the Revit ribbon

## What did you expect to see?

A button that starts Dynamo directly

## What did you see instead?

The version switcher.
While the version switcher is a nice idea, it would be far more helpful to have direct access to the various installed Dynamo versions. My main arguments:
- The version switcher is one more (unnecessary) click each time Revit is relaunched
- It makes it impossible to assign keyboard shortcuts for launching the various installed Dynamo versions

**Comment by sharadkjaiswal** [comment]
@andydandy74, I think you are talking about Dynamo on Revit 2017. If you have only one version of Dynamo installed then you can launch Dynamo in one click. After Dynamo 1.0 we are going to maintain a single version on the m/c until we move to Dynamo 2.0 which could be at least couple of releases away and we are still exploring how meaningful it would be to allow users to have both versions on the same m/c running with the same version of Revit. @kronz thoughts??

**Comment by andydandy74** [comment]
- I don't see any major differences between the 2016 and 2017 workflows. As long as I have several Dynamo versions installed, I will need to click twice to start Dynamo after launching Revit. Since Revit does not seem to like to release the memory Dynamo has been using, restarting Revit is a regular routine of my typical work day.
- Seeing that Dynamo 1.1 files seemingly cannot always be opened in Dynamo 1.0 (perhaps because of the new @@ stuff?), it would be very useful to still be able to install multiple 1.x versions side-by-side.
- Regarding the meaningfulness of having two versions installed side-by-side: I maintain a large number of Dynamo workflows not all of which may have been tested for the most current version installed at any time. That means I regularly have to switch between Dynamo versions, (Also, maintaining a package for several Dynamo versions entails having to switch versions frequently...)

**Comment by kronz** [comment]
@andydandy74 hmm, 1.1 files should ALWAYS open in 1.0 .  If you are finding otherwise we need to get on that right away.  Please share any files that don't go back?
cc @Benglin @riteshchandawar

**Comment by andydandy74** [comment]
This happened to @dimven recently - maybe he can share?

**Comment by riteshchandawar** [comment]
Hello, @andydandy74 If he was using any of the Daily builds then there might be a chance of he picked up the build which was having an issue with Backward compatibility., we have already rolled back those changes.  

@dimven Can you please share your file with us which was having an issue?

- Ritesh

**Comment by dimven** [comment]
@riteshchandawar I used the latest 1.1 daily at the time, so your explanation seems like it. I don't have the file any longer. I downgraded to 1.0 and rolled back the file to the version from the previous day.

**Comment by ikeough** [comment]
@andydandy74 I hate the version switcher too. It wouldn't exist if Revit plugins were sandboxed from one-another. But they're not. So, if you've already loaded one version of Dynamo for Revit, with dlls called something like...DynamoRevit.dll version 1.0.0, and you attempt to load another version of DynamoRevit.dll version 1.1.0, you'll get an error that you're not using the right version, because there's already a DynamoRevit.dll loaded in the AppDomain. The version switcher was the least-worst solution to allow you to pick a version of Dynamo to open. The only real solution is to sign all of our dlls, so you could have multiple versions of the same dlls loaded in the app domain. But it was decided a while ago that this was far more trouble than it was worth.

I hear you. I agree with you. But our hands are tied. If it were up to me, I would spend the Dynamo team's precious resource on only supporting one version of Dynamo on one version of Revit. Knowing that is not realistic given how people work with Dynamo and Revit, we continue to support multiple versions in the best way we can given the technical limitations.

If anyone reading this has any better ideas, I'm totally open to suggestions.

**Comment by andydandy74** [comment]
@ikeough - maybe I didn't communicate my suggestion clearly enough. I wasn't asking for the possibility to use more than one Dynamo version in the same Revit session - I understand why that doesn't work. 
This is the UI change that I had in mind:
**State of the ribbon after starting Revit:**
![onlaunch](https://cloud.githubusercontent.com/assets/3014437/17883135/08e604d2-6911-11e6-8196-d6f0af650517.png)
**State of the ribbon after starting one of the Dynamo versions** (in this case Dynamo 1.0):
![afterversionselection](https://cloud.githubusercontent.com/assets/3014437/17883146/2758263e-6911-11e6-8083-1b0f59132010.png)
This would allow for assigning keyboard shortcuts as well as save a click when selecting the desired Dynamo version after launching Revit. I don't know anything about coding menu items for the ribbon
so I don't know if that's possible, but the pre-1.0 version switchers did a fairly similar thing (i.e. change the ribbon content after Dynamo was launched the first time in a given session).
