### ISSUE TITLE
Issue with Parameter Type Node.

### ISSUE THREAD

**Issue by dhourihane** [DynamoDS/DynamoRevit#1406]
## Dynamo version

1.2.1.0
Core 1.2.0.2690
Revit 1.2.0.2690

## Revit version

2016
Build: 	16.0.490.0
		20150714_1515(x64)
		Service Pack 2

## Operating system

Windows 10

## What did you do? 

I connected the 3 nodes seen in the Image, selected an Element (a Floor) in Revit, and pressed 'Run'. I had originally run with just the first 2 Nodes connected to get the list of available Parameters.

## What did you expect to see?

I expected the 3rd Node to return a Parameter Type (it is a TEXT Parameter).

## What did you see instead?

See error message on image (screenshot).
![bug screenshot 20161127](https://cloud.githubusercontent.com/assets/23583286/20645027/aa1ea7e4-b445-11e6-9034-edbb818ba82c.png)

**Comment by ksobon** [comment]
@dhourihane The issue here is that the GetFamilyParameter node returns a String name of the Parameter Definition not the actual Parameter object. What you can do for now is this: 

![image](https://cloud.githubusercontent.com/assets/529781/20651121/e4f95dc0-b4ac-11e6-97cc-b9c8aa195066.png)

Yes, I agree this is strange and unexpected. I would either recommend that we change the output from the component to return `Revit.Elements.Parameter` or change the name of the port to `paramName` or something like that to prevent any confusion. 

cc: @mjkkirschner @kronz @moethu

**Comment by dhourihane** [comment]
Thanks @ksobon. Much appreciated.

**Comment by ksobon** [comment]
I would not close it yet. I think we have raised some valid issues here...

**Comment by ksobon** [comment]
cc @kronz and @mjkkirschner please see above. What do you think?

**Comment by ksobon** [comment]
@kronz do you agree that the `Get Family Parameter` node should actually be returning a parameter? Here's an example of what that would look like: 

![image](https://cloud.githubusercontent.com/assets/529781/26337695/99485e22-3f48-11e7-839c-253636b04e75.png)

It would require changes to both the dropdown node and the `Parameter` class. I think it's worth the hassle. It should be consistent like that.

**Comment by kronz** [comment]
@ksobon I think the Get Family Parameter node has typically been used in a Get and Set Parameter workflow, and returning a Parameter would break all of these.  It might be appropriate to rename it to Get Family Parameter Name, I suppose, but not to change it's function.
![2017-05-23_0930](https://cloud.githubusercontent.com/assets/3456818/26356666/c15cd26a-3f9a-11e7-945b-8d611456d941.png)

**Comment by ksobon** [comment]
@kronz I disagree. The node should return `Parameter` object. `Parameter` then has a `Name` property on it for those that want to go deeper. Again, this is a remnant from past times before there was a `Parameter` wrapper. However, you guys got all the usage data. Why don't you check how much this node get's used in that setting, and what damage it would do to change its use?

**Comment by kronz** [comment]
@ksobon Like I said, I'm all in favor of clarifying what this node does, we can at least make the output port say "string" or "name" instead of "parameter", and we could make an additional node that has the new functionality you are describing.  However it is getting used already, and pretty heavily.  The data is always a little odd to read in terms of intentions, and getting a node's neighbors is tricky, but I dug into the analytics and Get Family Parameter is apparently the 44th most used node, this puts it just behind All Elements of Family Type and Watch3d, and just ahead of Circle.ByCenterpointRadius and Select Face (half as popular as List.FilterByBoolMask, twice as popular as AdaptiveComponent.ByPoints).  That is, it seems to be fulfilling a need with the functionality it currently provides.  
It's possible that many of these uses are in association with Parameter.ParameterByName, as you have shown, we'd would have to do some deeper querying to find out.  But the result will almost certainly show that there are lots of workflows that have nothing to do with extracting the parameter of the element.
We have lots of ways of modifying behaviors, and we use them sparingly, and always with some kind of migration or warning.  This node is heavily used with the current functionality, we can clarify what it does in the naming conventions used, and we can add an additional node that has the behavior you describe.

**Comment by Chumpycmp** [comment]
I am talking from total ignorace from how the node work inside but...

may it be the easiest way to just have 2 outputs in the same node, one called paramters and one called names? For retrocompatibility old "parameters"  should be  rename as "names" and that is all.
