### ISSUE TITLE
RevisionCloud.ByCurves doesn't work on sheet view

### ISSUE THREAD

**Issue by sixtysecondrevit** [DynamoDS/DynamoRevit#1502]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1

## Revit version

2016

## Operating system

Windows 10

## What did you do? 

![image](https://cloud.githubusercontent.com/assets/15744724/22473966/bf8ff742-e797-11e6-999c-0819fc0939fc.png)

## What did you expect to see?

The revision clouds made in "paper space".

## What did you see instead?

An error (above), which seems to point to a sheet view being unable to support this. We typically place Revision clouds in "paper space" for ease of use in Revit, (and for schedules). Drawing them in this manner is typical for us.

**Comment by ksobon** [comment]
This has to do with the fact that currently Sheet class doesn't inherit from View but instead it inherits directly from Element. It also needs to be added to View class "annotation view" checklist that currently doesn't include Sheet views. That will be fixed with this PR: https://github.com/DynamoDS/DynamoRevit/pull/1672

![image](https://cloud.githubusercontent.com/assets/529781/26660236/949d8ea8-4644-11e7-81e0-64d1d2296558.png)

cc: @mjkkirschner @kronz

**Comment by ksobon** [comment]
@sixtysecondrevit @kronz this PR was merged already. Can we close this issue? cc: @BogdanZavu
