### ISSUE TITLE
List.Clean doesn't get delete null value at index 0

### ISSUE THREAD

**Issue by paoloemilioserra** [DynamoDS/DynamoRevit#1589]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.2.1.3083

## Revit version

2017.2

## Operating system

W7

## What did you do? 

(Fill in here)
![image](https://cloud.githubusercontent.com/assets/14221455/23454779/a5f63854-fe6d-11e6-9329-6ef3c567e9c8.png)

## What did you expect to see?

a list with only 2 PolyCurves

## What did you see instead?

the first element is still null

**Comment by dimven** [comment]
This is actually the expected behavior. If you want to remove all nulls, you'll need to set the preserveIndices input to false:
![dynamosandbox_2017-03-06_11-19-57](https://cloud.githubusercontent.com/assets/7148394/23595719/fed1d02e-025e-11e7-8ed4-a8cb3e638121.png)

The "explanation" of the functionality is hidden under the description of the input. Maybe that should be highlighted in the general node description as well?

**Comment by kronz** [comment]
Agree with @dimven
