### ISSUE TITLE
Parameter.Value error

### ISSUE THREAD

**Issue by Chumpycmp** [DynamoDS/DynamoRevit#1641]
## Dynamo version

Version 1.3.0.875

## Revit version

Revit 2016 Build 16.0.490.0 - 20150714_1515(x64)

## Operating system

Windows 7

## What did you do? 

Trying to get the Value from a Parameter in a Family loaded in the Family I am working. Using for that:
Family Types>Get Family Parameter>Parameter.Value

## What did you expect to see?
I was expecting to get the value of the parameter (a dimension)

## What did you see instead?
Instead I got an error in Parameter.Value "Warning: Internal error, please report: Dereferencing a non-pointer."
![error](https://cloud.githubusercontent.com/assets/5787607/24810228/e7a6d2ec-1bc1-11e7-8e03-4c395228eab7.png)
.

**Comment by ksobon** [comment]
cc: @kronz Zach the PR you closed would have addressed that. I know what you stated here: https://github.com/DynamoDS/DynamoRevit/pull/1688 and I get it, but that node really does make people think that a `Parameter` object is being returned from `Get Family Parameter`. It USED to make sense before we had all of the `Parameter` functionality, but now it makes no sense. 

@Chumpycmp this is happening because the value returned from `Get Family Parameter` is just the name of the parameter. It's a `String`. See here: https://github.com/DynamoDS/DynamoRevit/issues/1406

**Comment by kronz** [comment]
Sorry for the confusion, the current behavior is "as designed", although the terms used should be modified.  Please take a look at #1406 for more discussion.
