### ISSUE TITLE
Dynamo 2.0 node library is missing / isn't showing at all. 

### ISSUE THREAD

**Issue by mpguru66** [DynamoDS/DynamoRevit#1968]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo Core 2.0.0.4400
Dynamo Revit 2.0.0.4400

## Revit version

Revit 2018.2
## Operating system

Windows 10

## What did you do? 

Opened dynamo 2.0
## What did you expect to see?

Node Library 
## What did you see instead?

Blank
![dynamo library](https://user-images.githubusercontent.com/15841114/37842241-d6862db6-2e7e-11e8-9b41-3b3e8f9770a0.png)

**Comment by mjkkirschner** [comment]
remove pnid modeler from you revit installation /addins folder.

**Comment by mpguru66** [comment]
Michael,

Okay, thanks a lot.

On Fri, Mar 23, 2018 at 9:49 AM, Michael Kirschner <notifications@github.com

**Comment by dannysbentley** [comment]
![image](https://user-images.githubusercontent.com/6655476/39540495-a7a0a9ac-4df7-11e8-84c5-2747d70ddd69.png)

Revit 2018.2 
Dynamo 2.0 (just installed.)
Windows 8
Node Library is missing.  

What is the location of the pnid file? 

Same issue.

**Comment by jnealb** [comment]
Folder, just move it somewhere else in case you need it later.

**Comment by mjkkirschner** [comment]
@mengelmn what conflict message did raindrops introduce?

**Comment by mengelmn** [comment]
@mjkkirschner  - I received no message upon the addition of the package.  However Dynamo become immediatly slow to respond, at the point it did was the Libray was gone as in the original issue.  At this Time Dynamo was closed, Revit Restarted.  No Change, so then the I remove Raindrops, again restarted to be sure, no change.  Finally Removed Raindrops, and the Pnid Folder from both 2019 and 2018, restarted, reopend 2019, and still no library.

**Comment by krystal211** [comment]
I do not have a PNID folder in addins folder and this is still a problem with 2017. Any thoughts?

**Comment by WaynePatrickDalton** [comment]
Remove the NBS Plugin :wink:

**Comment by kilkellym** [comment]
I experienced the same issue. It had recently installed the UpCodes AI add-in. When I launched Dynamo, the library was missing. Uninstalling the add-in resolved the issue.

**Comment by Garrett-R** [comment]
Hey, I work with UpCodes.  Just became aware of this thread.  I'm not able to get a repro with our addin in Revit 2018.  My theory is that this could have to do with CEF (Chromium Embedded Framework).  Before Revit 2019.1, a couple addins used CEF (including at least one cited above), but sometimes that caused strange interactions between the plugins.  Does anyone know if Dynamo relies on CEF at all?  (if not, then this theory is wrong)

If this is the problem, there's not much that can be done about that.  You may have to just try uninstalling plugins one at a time until the library comes back.  It was effectively fixed in Revit 2019.1, so if anyone see this issue in that version or later with the UpCodes AI addin, shoot us an email at support@up.codes.  We're very responsive.  Or just leave a comment here.

**Comment by mjkkirschner** [comment]
Hi @Garrett-R dynamo 2.x uses CEF - version 57 - we moved to cef 65 on master.

**Comment by Garrett-R** [comment]
@mjkkirschner sweet, that must be it then.  That explains the non-deterministic behavior.

I'd be curious to hear your decision to move from v57 to v65 (besides it being newer and better of course) and whether that works with Revit 2019.1+.

Since Revit 2019.1, [Revit is now the first one to initialize CEF](https://forums.autodesk.com/t5/revit-api-forum/revit-2019-1-add-in-and-cefsharp-library/td-p/8205740) and it chooses v57.0.0 (whereas before it was a non-deterministic free-for-all to see who initialized it first).  CEF can only be initialized once per process I believe (I'm a bit shaky there).  Does Dynamo run in a separate process or something such that it doesn't have to share CEF with Revit (and the addins also using CEF)?

**Comment by QilongTang** [comment]
@Garrett-R You are totally right. All the addins/addons I am aware of are running in the same process with Revit UI which is forcing DynamoRevit ( addin starting from R2020, addon before R2019) to align the same CEF version with Revit host for now

**Comment by DclearEE** [comment]
Revit 2018.3.3 (Fresh installed)
Dynamo 2.03 (Fresh installed.)
Windows 10
Node Library is missing.

I can still right-click and search for nodes. I tried deleting PNID Modeler and my dynamo packages but nothing changed.
Have there been any new discoveries on how to fix this yet? This problem is very annoying and only occurs in Revit 2018. Revit 2019 and 2020 work fine with dynamo 2.03
