### ISSUE TITLE
Views List not ordered alphabetically

### ISSUE THREAD

**Issue by moni87d** [DynamoDS/DynamoRevit#2023]
## Dynamo version

1.3.2

## Revit version

Revit 2017

## Operating system

Windows 10

## What did you do? 

Used the Views node

## What did you expect to see?

Views sorted alphabetically

## What did you see instead?

Views NOT sorted alphabetically

**Comment by andydandy74** [comment]
@mjkkirschner Well, it would make sense to have all dropdowns ordered alphabetically, wouldn't it? Especially on large projects that easily have a high three figure number of views. The ```Family Types``` dropdown node is a good precedent, I think.
I originally reported this for Dynamo 1.1 (#1264). It was fixed by @ksobon (#1316) but I think that PR never got merged in the end.

**Comment by moni87d** [comment]
@mjkkirschner I think @andydandy74 gave the perfect explanation for me already. 
The node is impossible to use at the moment, particularly if you have a project with hundreds/thousands of views.

**Comment by ksobon** [comment]
@andydandy74 2.0 has it sorting properly. 
![image](https://user-images.githubusercontent.com/529781/39411674-a7285bfe-4bdc-11e8-8199-75a8df5ca232.png)

problem solved?

**Comment by andydandy74** [comment]
Sure. Never bothered to look whether this was fixed in 2.0 ... :-)

**Comment by moni87d** [comment]
@ksobon thanks... will wait patiently until I can get 2.10 then
