### ISSUE TITLE
Image.Pixel sample offset

### ISSUE THREAD

**Issue by alramhtims** [DynamoDS/DynamoRevit#2212]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

2.0

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

2019.1

(Which version of Revit are you using?)

Windows 8.1 Enterprise

(e.g. Windows 7, Windows 8.1, etc)

Sampled an image with the Image.Pixels node

## What did you expect to see?

The image was symmetrical, the resulting values should have been symmetrical.

## What did you see instead?

The values appear to be sampling starting at 0,0 instead of the center of the first sample square and this is throwing the values off.

You can download the files from the Forum post:
https://forum.dynamobim.com/t/image-pixel-symmetry/26958?u=marla_smith

**Comment by mjkkirschner** [comment]
Hi @alramhtims I think you might be right.
https://github.com/DynamoDS/Dynamo/blob/ec10f936824152e7dd7d6d019efdcda0d78a5264/src/Libraries/CoreNodes/FileSystem.cs#L372

It looks to me like the expression should be 
 `Color.ByColor(image.GetPixel(x * (image.Width / (numX-1)), y * (image.Height / (numY-1)))))`

because numx is not the max value of x but the number of x and x will never be equal to that number. so we'll never get a value which is equal to the max image width or image height.

**Comment by QilongTang** [comment]
This is verified in Dynamo 2.1
![image](https://user-images.githubusercontent.com/3942418/49060487-b4e77680-f1db-11e8-856d-6fb2b1ca2117.png)
