### ISSUE TITLE
Searching in the Node Library VERY slow

### ISSUE THREAD

**Issue by pfaubin** [DynamoDS/DynamoRevit#2236]
## Dynamo version
2.0.1
## Revit version
2019.1
## Operating system
Windows 10
## What did you do? 
Searching in the node library is very slow for me. There is a long lag between each letter you type. 

Is this something that others have seen? Can it be corrected? Thanks.

**Comment by AkuJokinen** [comment]
I have had same problem for a long time. The lag seems to be increasing by every custom package installed. I also remember someone saying somewhere that the problem with extremely slow search might be due to having custom packages folder on shared location (eg. local server/NAS). That's how we have set up things in our office in order to have custom packages in sync between users.

**Comment by eibre** [comment]
I have the same problemt too. Removed all custom packages and it gets better, but it would be nice to have the packages installed.

**Comment by ZiyunShang** [comment]
Hi @pfaubin , I think you can relate to https://github.com/DynamoDS/DynamoRevit/issues/2415#issuecomment-519668098 .
It's better that you can use the latest version of Dynamo.

**Comment by ZiyunShang** [comment]
I closed this issue, and it will be reopened when there are some new info.
