### ISSUE TITLE
Dynamo isn't opening.  Only has white screen. 

### ISSUE THREAD

**Issue by dannysbentley** [DynamoDS/DynamoRevit#2347]
Dynamo 2.0.2
Revit 2018 and 2019
Operating system Windows 7 Enterprise 
What did you do? 

This is what I tried to do to solve the problem. 
I uninstalled 2.0.2. 
I reinstalled 2.0.2
I restarted my computer.  

What did you expect to see?
I just want Dynamo to open. 

What did you see instead?
The screen is white like it's stuck. 
![errornotopening](https://user-images.githubusercontent.com/6655476/52736936-ef151880-2f7f-11e9-88c2-8013f339dac7.PNG)

**Comment by mjkkirschner** [comment]
I think @JacobSmall had a solution for this but I can't find the forum thread atm.

**Comment by dannysbentley** [comment]
Something strange happened.  I was giving a presentation and used a different window/resolution size.  When I came back to my computer it had gone off my screen.  I turned off my monitor and it reset and gave me the Dynamo window. 

It works now.  The odd part is why it gave me a white window.

Thanks.

**Comment by JacobSmall** [comment]
When I’ve see. This happen it’s been due to the window being off screen. The graphics card having to recalculate the window’s coordinates often fixes it as you kind of described above. 

Another fix is to use a windows command (win key + left arrow several times, or win key + right arrow several times, or alt + space > any arrow > move the mouse).
