### ISSUE TITLE
Topography.Points not working

### ISSUE THREAD

**Issue by kazuhiko1583** [DynamoDS/DynamoRevit#2379]
If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
Dynamo 1.3.3 & 2.0.1

## Revit version

Revit 2019.2

## Operating system
Windows 10

## What did you do? 

Try to extract the points from topography, using topography.point function.
Dynamo 1.3.3 & 2.0.1 both not working
<img width="960" alt="001" src="https://user-images.githubusercontent.com/50065249/56858472-0f644900-69ad-11e9-91a6-4b6aea35b535.png">

## What did you expect to see?

Get the point from topography
The same script is working on Revit 2018.3, 2019.0

![002](https://user-images.githubusercontent.com/50065249/56858499-69650e80-69ad-11e9-9193-b5e1ac4a0947.PNG)

## What did you see instead?

Warning message as shown in the first screenshot

**Comment by dimven** [comment]
I have a slight suspicion that you need Dynamo 2.0.**2** specifically for Revit 2019.2, because they made changes to the geometry kernel (it has a higher version of ShapeManager / LibG and needs updated hooks).

Better yet, try using 2.0.3, if possible, so that you get the benefit of a working library..

**Comment by mjkkirschner** [comment]
thanks @dimven 100% correct. Use 2.0.2 or higher.
