### ISSUE TITLE
Dynamo Core nodes showing as unresolved

### ISSUE THREAD

**Issue by OliverEGreen** [DynamoDS/DynamoRevit#2642]
## Dynamo version
V2.0.4

## Revit version
Revit 2018 / 2019
(Please Note: This is not an issue with Revit 2020+/Dynamo 2.1+)

## Operating system
Windows 10

## What did you do? 

Opened .rvt files in either Revit 2018 or 2019, then opened existing definitions in Dynamo 2.0.4.

## What did you expect to see?

Core nodes should be resolved automatically.

## What did you see instead?

![image (5)](https://user-images.githubusercontent.com/29973601/96578804-b2a9cc00-12cd-11eb-92d4-f7be7f00da5f.png)

Many Dynamo Core nodes in existing definitions (such as Watch, Categories, Python Script) are showing up as unresolved (see image). These are not nodes from custom packages. Re-placing these unresolved core nodes from the library solves the problem and they work as they should. But when the definition is saved and re-opened, the nodes are unresolved again.

Our office upgraded to Dynamo 2.X from 1.X earlier this year. The timing of this issue appears to coincide with this upgrade. Old definitions have generally appeared to upgrade well and only specific users are reporting this unresolved core nodes bug.

So far, we have not established a reliable pattern which may be causing this. The Dynamo console and logs are not giving us any useful clues. We have tried uninstalling our plugins (Revit ExternalApplication and Dynamo ViewExtension) and all external node packages, which has not helped. This does not appear to be an obvious package / plugin conflict issue.

@mjkkirschner  @aparajit-pratap , we are a large organisation using many Dynamo definitions in our day-to-day workflows.
Any help in identifying what's causing this issue would be gratefully received.

**Comment by mjkkirschner** [comment]
This is very likely an issue with an Addin, not a package.
I would remove all addins with something like the addin manager or remove all addin manifests in batches.

**Comment by OliverEGreen** [comment]
Hi Michael, 

It seems this is a conflict issue with one of the usual suspects - the NBS plugin for Revit.
It seems the plugin is storing / retrieving data in specific projects, which is why this issue is on reproducible in particular files and for particular users. I am aware this is a CefSharp issue. 

Do you know if any solutions have been found, bar removing the plugin?

Thanks
Ollie

**Comment by mjkkirschner** [comment]
I think the first step is to reach out to the authors of the plugin to see if they are aware of the issue.

This is sometimes caused when the addin subscribes to an `assemblyResolve` event and throws an exception while looking for an assembly.

We cannot control what order assembly resolve handlers are called in, so what may happen is that when Dynamo tries to look for an assembly, the other addins resolve handler is triggered first, if the assembly cannot be found, it should return null instead of throw.

I've seen other addins work around this issue by trying to only respond to resolve requests that come from their own assemblies.

**Comment by mjkkirschner** [comment]
Hi @OliverEGreen I've closed this for now, but curious if there was a resolution?

**Comment by AhmmTools** [comment]
Hi @mjkkirschner, it is down to the NBS plugin. I know we've had conflict issues between Dynamo and the NBS before with the different versions of the CefSharp library being used, but this doesn't seem to be the case this time around. NBS made changes to later versions of their addin so that both referenced CefSharp versions were perfectly aligned.

Other UK architecture firms have also reported this problem, so we're attempting to deal with this via the developers.

What's interesting is that this issue only seems to happen with particular files. My guess is that once the NBS plugin has been used, it stores information in the file via ExtensibleStorage (yet to test this part of the theory out). Once a user opens one of these files, part of the NBS addin runs and this is what causes the conflict.
