### ISSUE TITLE
Memory Corruption With Ellipses In Revit 2022 With Dynamo 2.10

### ISSUE THREAD

**Issue by karambk** [DynamoDS/DynamoRevit#2699]
## Dynamo version

2.10

## Revit version

Revit 2022

## Operating system

Windows 10

## What did you do? 

Draw Ellipse in Revit (Model Line)
Select This Ellipse and Get It's Curve (Element.Curves) 
Split This Ellipse Using Curve.SplitByParameter, For Example With Parameter 0.5
Explode The Result to Return Original Geometry (EllipseArc)
Plug It Into Geometry Scale
![RevitScreen](https://user-images.githubusercontent.com/74302224/116595902-7dd99a00-a92c-11eb-9649-657edfeee9b7.png)

## What did you expect to see?

No Errors With The Ability to Change Scale

## What did you see instead?

Warning: Geometry.Scale operation failed. 
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

## More Info
This issue might sound "not dangerous", but it is affecting many workflows that has ellipse involved with Revit, as it seems it also breaks the geometry conversion of Dynamo Ellipse into Revit Ellipse.. In short, a total disability to use edited Ellipse (Split in this case).

The issue came to light after Revit 2022 has shipped Dynamo 2.10.
As earlier versions shipped 2.6 which didn't have this Bug.

Finally, I already prepared a .zip file contains SAT and DYN file for faster tests and reproducing of the problem.
[MemoryCorruption.zip](https://github.com/DynamoDS/DynamoRevit/files/6400677/MemoryCorruption.zip)

Please note that if you tried the DYN file that imports the SAT file which contains the EllipseArc in Dynamo Sandbox, it works correctly..
The problem happens only in Dynamo 2.10 INSIDE REVIT 2022

**Comment by mjkkirschner** [comment]
I've tracked this internally with: https://jira.autodesk.com/browse/DYN-3661 - we can take a look and see if we can reproduce in sandbox - it could be like you observe something in Revit having changed, but that would be surprising.

**Comment by karambk** [comment]
@mjkkirschner it actually surprised me, I couldn't reproduce it in Sandbox, not in 2.10 nor in 2.11 nor in 2.11.1

However the problem always happen in Revit 2022 with Dynamo 2.10

**Comment by mjkkirschner** [comment]
🔍  !

**Comment by mjkkirschner** [comment]
Hi @karambk - I've looked at this quite closely.

I can reproduce the crash/access violation in 2.10 - when comparing dynamo in revit to dynamo in sandbox - especially when dealing with geometry issues - it is imperative to make sure you are debugging against the same version of the geometry library.

To do this, you can use the -gp flag - see the docs on it here:
https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Command-Line-Interface

1. I used this to force sandbox to use the same version of the geometry library as Revit 2022 - and your graph causes a hard crash.

2. then I tested against 2.11 - also forcing the same version of the geometry library - this did not crash.
3. I've tracked down the issue to a fix right around the 2.10 release timeframe - I believe the fix is in some of the geometry branches, but not others - explaining why you might see sandbox not crash if it loads one of the older versions - but crash when forced to load against a specific version - like in Revit.

In any case - the issue is already fixed in core for all branches, and can be integrated by the revit team by grabbing 2.11.

**Comment by karambk** [comment]
@mjkkirschner That's super useful information, thank you for the efforts and the insights, I'll take into consideration those notes in future findings and issues.

It's relieving to know the issue is fixed in 2.11
