### ISSUE TITLE
Categories dropdown node missing several categories

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoRevit#982]
A while ago I reported that several categories in the `Categories` dropdown node were producing a warning. For a list of the affected categories and more information about the original issue, please refer to https://github.com/DynamoDS/Dynamo/issues/4117

Apparently, the "fix" for this was to remove those categories from the dropdown entirely. This may sound harsh, but to me that is **not** a fix, it is **ignoring** the problem. The image below shows that 
a) these categories are present in a Revit model (test was run on R2016) and
b) they can be queried with a `FilteredElementCollector`.

![bic](https://cloud.githubusercontent.com/assets/3014437/15039796/f52cd98c-12af-11e6-9dab-75b2e05a1318.PNG)

If these categories are not supported we are back where we were with Dynamo 0.6 before the `Categories` and `All Elements of Category` nodes with people having to write their own Python-based`FilteredElementCollector` nodes to retrieve elements from the model.
Please provide a **proper** fix.

**Comment by sharadkjaiswal** [comment]
@andydandy74, thanks for reporting it. I think it's an issue with the Revit API, we are using Autodesk.Revit.DB.Category.GetCategory to track the categories available in Document and for many of these built-in categories it returns null, which we removed from the drop down. We need to check if there are other APIs that provide a valid category from a given built-in category.

**Comment by jnealb** [comment]
@sm6srw fyi

**Comment by ksobon** [comment]
@andydandy74 I know this is a little frustrating but let me explain what is happening here so that we all on the same page: 

You are using `Enum.GetValues(BuiltInCategory)` to retrieve all of the built in categories from the model. That returns 1005 objects in my Revit 2018. Now a lot of these objects represent so called "internal" or "obsolete" categories. Here's an example: 

![image](https://user-images.githubusercontent.com/529781/27006580-7c5f2c2a-4e05-11e7-8c2f-e74ea30b093d.png)

All of the internal and obsolete categories don't actually have a `Category` object (don't confuse with `BuiltInCategory` object) stored in the model that is accessible via available API methods. That's pretty understandable. 

All of the publicly available `Category` objects are stored in the `Document.Settings.Categories` which returns a list of "top level categories" aka Parent Categories. You can drill down that list for all Sub Categories. If you were to return all of these you get roughly 627 objects. 

![image](https://user-images.githubusercontent.com/529781/27006619-7337234a-4e06-11e7-9954-a82926cfa04c.png)

I highlighted parent category in each sub-list and the rest of them are publically available sub-categories. As you can see "Reveals" are not on that list. Well that's weird right? You can make a Wall Reveal and using the Lookup Tool it will report this: 

![image](https://user-images.githubusercontent.com/529781/27006625-c2a5247c-4e06-11e7-9264-215596587a88.png)

So it clearly states that `WallSweep` is a Category object. It has a Parent category of `Walls`. How is it possible that Reveals reports its parent to be Walls, but Walls doesn't report Reveal as its child? That in all honesty is a question for Autodesk brass. Something really fishy is going on here. 

Now, that OST_Reveals BUILT IN CATEGORY does exist in the model. I get it. You can also use it with `FilteredElementCollector`. I get that too. That method accepts BuiltInCategory so everything is dandy. There is only one problem. We don't have any means of accessing its `Category` object because methods like `Category.GetCategory()` only draw from the `Document.Settings.Categories` pool of categories and as we just found out that particular one doesn't exist there. 

I would conclude this rather lengthy response with a simple: you are both right @sharadkjaiswal and @andydandy74. Revit developers somehow managed to mess this up, and as is right now, neither of us can do anything about this situation. Yes, Andy, you are left to using Python and custom nodes for some of these left out, obsolete or internal categories because FilteredElementCollector somehow still works on those. @sharadkjaiswal our implementation of the category dropdown seems about right to me. I don't see why we would need to change anything. 

Cheers!

**Comment by ksobon** [comment]
cc: @kronz if you agree with my assessment here, can we close this issue?

**Comment by kronz** [comment]
Wow, thanks for the in depth analysis @ksobon 
Agreed, closing.

**Comment by andydandy74** [comment]
Fair enough. Custom node it is then. ;-)
